@startuml

title Pet Sitting App Class Diagram v0

enum Role {
  PET_OWNER
  PET_SITTER
}

class User {
  -name: String
  -email: String
  -phoneNumber: String
  -password: String
  -role: Role
  +register(): void
}

class PetOwner {
  -pets: Pet[]
  +addPet(pet: Pet): void
}

class PetSitter {
  -experience: String
  -qualifications: String
  -availability: String
  -services: String
  +addAvailability(time: String): void
  +addService(service: String): void
}

class Pet {
  -name: String
  -breed: String
  -age: Integer
  -careInstructions: String
}

User <|-- PetOwner: <<inherits>>
User <|-- PetSitter: <<inherits>>
PetOwner "1" *-- "0..*" Pet: owns
@enduml
