@startuml
Title: PetS Class Diagram

package "App" {

  class Main {
      - UI
      - ServerProxy
      +Main()
      +initialize()
      +shutdown()
      +startApplication()
      +handleUserInput()
      +loadData()
      +saveData()
  }
    
  class UI {
      -String currentPage
      -User currentUser
      -Pet currentPet
      -HashMap<String, UserInput> userInputFields
      -HashMap<String, Component> components
      + renderHomeScreen()
      + renderLoginScreen()
      + renderUserProfile()
      + renderPetProfile()
      + updateUserInfo()
      + updatePetInfo()
      + showAvailablePetSitters()
      + showAppointments()
      + showPaymentPage()
      + handleErrorMessages()
  }
  
  class ServerProxy {
      - APIProxy apiProxy
      - DatabaseProxy databaseProxy
      + clientToServer()
      + serverToClient()
      +initialize()
      +shutdown()
      +syncDataWithServer()
      +handleServerError()
  }

  class API {
      -String baseURL
      -String apiKey
      -HashMap<String, String> headers
      +sendRequestToServer()
      +receiveResponseFromServer()
      +handleAPIErrors()
      +fetchUserData()
      +fetchPetData()
      +fetchAvailablePetSitters()
  }

  class Database {
      -String userTable
      -String petTable
      -String password
      -String appointmentTable:
      +sendQueryToDatabase()
      +receiveResultsFromDatabase()
      +updateDatabase()
      +handleDatabaseErrors()
  }
  
  Main "1" *-- "1" UI
  Main "1" *-- "1" ServerProxy
  ServerProxy "1" *-- "1" API
  ServerProxy "1" *-- "1" Database
}


package "Server" {

  class Main {
    -String serverName
    -User[] users
    -Appointment[] appointments
    -Payment_Gateway[] paymentGateways
    -Database database
    +initializeServer()
    +loadUsers()
    +manageAppointments()
  }

  class "Payment_Gateway" {
    -String transactionId
    -float amount
    -String paymentStatus
    +ProcessPayment(User_Account)
    +RefundPayment(User_Account)
    +CheckTransactionStatus()
  }

  class User {
    -UserType type
    -String name
    -String contact
    -Appointment[] appointments
    +register()
    +manageProfile()
  }

  class PetOwner {
    -Pet[] pets
    -Appointment[] requestedAppointments
    +searchPetSitter()
    +viewPetSitterProfile()
    +requestAppointment()
    +manageAppointments()
    +makePayment()
    +rateAndReview()
    +selectAppointmentDays()
    +confirmAppointment()
    +updateAppointment()
    +cancelAppointment()
  }

  class PetSitter {
    -int yearsExperience
    -Appointment[] receivedAppointments
    -String name
    -String location
    -float rating
    -Appointment[] appointments
    +AcceptAppointment(Appointment)
    +RejectAppointment(Appointment)
    +ReceivePayment(Appointment)
    +RespondToReview(Pet_Owner, response)
  }

  class Pet {
    -String name
    -String breed
    -Date birthdate
    -String specialNeeds
    +setPetDetails()
    +getOwner()
    +setOwner(PetOwner)
  }

  class Appointment {
    -Date date
    -Time startTime
    -Time endTime
    -PetSitter sitter
    -PetOwner owner
    -boolean confirmed
    -Payment payment
    +ConfirmAppointment()
    +ScheduleAppointment(date, time)
    +CancelAppointment()
  }

  class Review {
    -float rating
    -String comment
    +writeReview()
  }

  class "Database" {
    -String databaseName
    -String databaseUrl
    +ConnectToDatabase()
    +RetrieveData()
    +StoreData()
    +UpdateData()
    +DeleteData()
  }

  Main "1" -- "0..*" User : manages
  Main "1" -- "0..*" Payment_Gateway : processes
  Main "1" -- "1" Database : owns

  User <|-- PetOwner
  User <|-- PetSitter
  PetOwner "1" -- "*" Pet : owns
  Appointment "1" -- "1" Pet : Care-of
  PetSitter "1" -- "*" Appointment : employment
  PetOwner "1" -- "*" Review : Makes

}


@enduml
