@startuml
title: UC-11: Select Appointment Days - Sequence Diagram
actor PetOwner
entity "User Interface (UI)" as UI
box "App core" #LightYellow
  entity "Appointment Manager" as AppCore
end box
entity "API Server" as API
database "Database" as DB

PetOwner -> UI : Selects desired appointment days
activate UI

UI -> AppCore : Sends selected appointment days
activate AppCore

AppCore -> API : Sends selected appointment days
activate API

API -> DB : Updates desired appointment days in database
activate DB

DB --> API : Returns appointment selection status
deactivate DB

API --> AppCore : Returns appointment selection status
deactivate API

AppCore --> UI : Updates appointment selection status
deactivate AppCore

UI --> PetOwner : Displays appointment selection status
deactivate UI

@enduml

